### PR TITLE
fix for Xcode scheme name match and turn the Xcode project into a Swift Package

### PR DESCRIPTION
**Pull request by heyzooi**
For cases when the schemes are like:

- MyProject
- MyProject-macOS

Specifying the scheme name as `MyProject` both schemes were matching

### CODE REVIEW

**Comment by heyzooi** [comment]
I signed it!

**Review by jverkoey — APPROVED** [review]

**Comment by jverkoey** [comment]
Thank you!

**Comment by jverkoey** [comment]
Looks like travis ci failed?

**Comment by heyzooi** [comment]
@jverkoey it failed because travis ci have a limitation that stops the build if no output is produced in 10 minutes. this usually happens when the travis ci virtual machines are too slow or freezing for some reason.

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

Could you please start the build again?

**Comment by jverkoey** [comment]
Looks like CI isn’t working in general so we’ll need to follow up on that separately.

**Pull request merged**
